<?php

namespace App\Services;

use PhpOffice\PhpPresentation\IOFactory as PresentationFactory;
use PhpOffice\PhpSpreadsheet\IOFactory as SpreadsheetFactory;
use PhpOffice\PhpSpreadsheet\Writer\Pdf as PdfWriter;
use PhpOffice\PhpWord\IOFactory as WordFactory;
use TCPDF;

class OfficeFileConversion
{
    public function convertToPdf($filePaths, $newFilePath)
    {
        // Use the dynamic file path provided as argument
        // $filePath = $filePathss;
        $filePath = 'C:\wamp64\www\airtellms\public\training_document\SEP2024\1726133648-document.docx';

        $extension = strtolower(pathinfo($filePath, PATHINFO_EXTENSION));

        switch ($extension) {
            case 'doc':
            case 'docx':
                $phpWord = WordFactory::load($filePath);
                \PhpOffice\PhpWord\Settings::setPdfRendererName(\PhpOffice\PhpWord\Settings::PDF_RENDERER_TCPDF);
                \PhpOffice\PhpWord\Settings::setPdfRendererPath(base_path('vendor/tecnickcom/tcpdf'));

                $pdfWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'PDF');
                $pdfWriter->save($newFilePath);
                break;
            case 'xls':
            case 'xlsx':
                $spreadsheet = SpreadsheetFactory::load($filePath);
                $pdfWriter = new PdfWriter\Dompdf($spreadsheet);
                $pdfWriter->save($newFilePath);
                break;
            case 'ppt':
            case 'pptx':
                $this->convertPptToPdf($filePath, $newFilePath); // Call the new method
                break;
            default:
                throw new \Exception("File format not supported for conversion.");
        }

        return $newFilePath;
    }
    public function convertPptToPdf($filePath, $newFilePath)
    {
        try {
            // Load the presentation file
            $presentation = PresentationFactory::load($filePath);

            // Initialize TCPDF
            $pdf = new TCPDF();
            $pdf->SetCreator(PDF_CREATOR);
            $pdf->SetAuthor('Generated by PhpPresentation');
            $pdf->SetTitle('PPT to PDF');
            $pdf->SetMargins(0, 0, 0);
            $pdf->setPrintHeader(false);
            $pdf->setPrintFooter(false);

            // Loop through each slide in the presentation
            foreach ($presentation->getAllSlides() as $slideIndex => $slide) {
                // Create a new page in the PDF for each slide
                $pdf->AddPage();

                foreach ($slide->getShapes() as $shape) {
                    if ($shape instanceof \PhpOffice\PhpPresentation\Shape\RichText) {
                        foreach ($shape->getParagraphs() as $paragraph) {
                            foreach ($paragraph->getFont() as $font) {
                                $panose = $font->getPanose();
                                if (mb_strlen($panose) !== 10) {
                                    // Set a default valid Panose value
                                    $font->setPanose('0000000000'); // Example default Panose value
                                }
                            }
                        }
                    }
                }

                // Save the slide as an image using GD
                $imagePath = $this->saveSlideAsImageWithGD($slideIndex);

                // Add the image to the PDF
                if (file_exists($imagePath)) {
                    $pdf->Image($imagePath, 0, 0, $pdf->getPageWidth(), $pdf->getPageHeight());
                }
            }

            // Output the PDF to the specified path
            $pdf->Output($newFilePath, 'F');

        } catch (\PhpOffice\PhpPresentation\Exception\InvalidParameterException $e) {
            \Log::error('Panose value error in PPT conversion: ' . $e->getMessage());
        }
    }



    // Helper function to save each slide as an image using GD Library
    private function saveSlideAsImageWithGD($slideIndex)
    {
        // Generate the path to store the slide image
        $imagePath = public_path('training_document/slides/slide-' . $slideIndex . '.png');

        // Create a blank image canvas with GD
        $width = 1280; // Example width for the slide image
        $height = 720; // Example height for the slide image
        $image = imagecreatetruecolor($width, $height);

        // Set white background color
        $white = imagecolorallocate($image, 255, 255, 255);
        imagefill($image, 0, 0, $white);

        // Draw slide number text onto the image (customize as needed)
        $black = imagecolorallocate($image, 0, 0, 0);
        imagestring($image, 5, 10, 10, "Slide " . ($slideIndex + 1), $black);

        // Save the generated image
        imagepng($image, $imagePath);
        imagedestroy($image);

        return $imagePath;
    }
}
